name: Deploy to Kubernetes

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.K8S_KEY }}
      
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: hopeful-keep-480204-e0
    
      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/hopeful-keep-480204-e0/uwb/uwb-app:latest .
    
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
    
      - name: Push image
        run: |
          docker push us-central1-docker.pkg.dev/hopeful-keep-480204-e0/uwb/uwb-app:latest
    
      - name: SSH into VM and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.K8S_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          passphrase: ${{ secrets.VM_SSH_PASSPHRASE }}
          script: |
            export KUBECONFIG=$HOME/.kube/config
            cd ~/app
            kubectl apply -f k8s/deployment.yaml --validate=false
            kubectl apply -f k8s/service.yaml --validate=false
            kubectl rollout status deployment/uwb-app --timeout=120s
