name: Deploy to Kubernetes

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: YOUR-PROJECT-ID

    - name: Build Docker image
      run: |
        docker build -t gcr.io/hopeful-keep-480204-e0/uwb-app:latest .

    - name: Authorize Docker push
      run: |
        gcloud auth configure-docker gcr.io

    - name: Push image
      run: |
        docker push gcr.io/hopeful-keep-480204-e0/uwb-app:latest

    - name: SSH into VM and deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.K8S_HOST }}
        username: ${{ secrets.K8S_USER }}
        key: ${{ secrets.K8S_SSH_KEY }}
        script: |
          cd ~/app
          git pull origin main
          kubectl apply -f k8s/
